version: '3.3'

services:
  postgres:
    image: postgres
    container_name: cscl_db
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cscl
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed/:/docker-entrypoint-initdb.d/:ro
volumes:
  postgres_data:
